In [5]:
from time import perf_counter
import numpy as np

N = 3

A = np.random.rand(N,N)
B = np.random.rand(N,N)

t1 = perf_counter()

C = A@B        

t2 = perf_counter()

dt = t2 - t1

print(f"Tiempo transcurrido = {dt} s")

Tiempo transcurrido = 0.00016440000001693988 s


In [9]:
print(A)
print(B)

[[0.45890945 0.8189742  0.09890353]
 [0.86443811 0.18510825 0.95283016]
 [0.12657405 0.11762482 0.06431828]]
[[0.72854729 0.07998244 0.63264362]
 [0.52425584 0.34848142 0.52730495]
 [0.65663414 0.59831516 0.64927795]]


In [10]:
A

array([[0.45890945, 0.8189742 , 0.09890353],
       [0.86443811, 0.18510825, 0.95283016],
       [0.12657405, 0.11762482, 0.06431828]])

In [11]:
C

array([[0.81319591, 0.64849353, 0.70820223],
       [0.63471747, 0.45743801, 0.32042755],
       [0.85058907, 0.71257002, 0.89706996]])